language: c
sudo: required
dist: trusty
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash .travis-extra-deps.sh
env:
  global:
    - OPAMVERBOSE=y
    - POST_INSTALL_HOOK="bash .travis-test-compile.sh"
  matrix:
    - OCAML_VERSION=4.03
    - OCAML_VERSION=4.06
os:
  - linux
  - osx
